services:
  bolo237-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: bolo237-admin:latest
    container_name: bolo237-admin-portal
    ports:
      - "3001:3000"
    restart: unless-stopped
    env_file:
      - .env
